
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbjbnfcmzkkubkklqqlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiamJuZmNtemtrdWJra2xxcWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTgzMDIsImV4cCI6MjA1OTgzNDMwMn0.pOfIG_TkxLsajAGAPSYTD6395akldm_enPrvGIg1NKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: We're using 'any' here because the generated types don't include all tables yet
// This is a temporary workaround until the types are updated
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
